baseURL: "/"
languageCode: en-us
defaultContentLanguage: en
theme: almeida-cv
title: CV Guillaume Biessy
params:
  colorDark: '#666'
  colorLight: '#fff'
  colorPageBackground: '#ddd'
  colorPrimary: 'red'
  colorPrimaryText: '#fff'
  colorRightColumnBackground: '#f5f5f5'
  colorSecondary: '#aaa'
  pages: 2
markup:
  goldmark:
    renderer:
      unsafe: true
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
